/// Domain 2: one row per order from order_history_clean (Food Delivery Order History, Delhi NCR,
/// Sep 2024 - Jan 2025). Its own platform and ID space - never relate it to Customers/Restaurants/Orders.
table OrderHistory

	column order_id
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: order_id

	column restaurant_name
		dataType: string
		summarizeBy: none
		sourceColumn: restaurant_name

	column subzone
		dataType: string
		summarizeBy: none
		sourceColumn: subzone

	column order_placed_at
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		summarizeBy: none
		sourceColumn: order_placed_at

	/// Date part of order_placed_at, related to Calendar.
	column OrderDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: OrderDate

		annotation UnderlyingDateTimeDataType = Date

	/// Hour of day the order was placed (0-23).
	column order_hour
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: order_hour

	column order_status
		dataType: string
		summarizeBy: none
		sourceColumn: order_status

	column discount_construct
		dataType: string
		summarizeBy: none
		sourceColumn: discount_construct

	column has_discount
		dataType: boolean
		summarizeBy: none
		sourceColumn: has_discount

	column bill_subtotal
		dataType: double
		formatString: "₹"#,0.00
		summarizeBy: none
		sourceColumn: bill_subtotal

	column total
		dataType: double
		formatString: "₹"#,0.00
		summarizeBy: none
		sourceColumn: total

	/// Customer rating 1-5. Blank for the ~88% of orders that weren't rated.
	column rating
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: rating

	column cancellation_reason
		dataType: string
		summarizeBy: none
		sourceColumn: cancellation_reason

	column kpt_duration_minutes
		dataType: double
		formatString: 0.0
		summarizeBy: none
		sourceColumn: kpt_duration_minutes

	column rider_wait_time_minutes
		dataType: double
		formatString: 0.0
		summarizeBy: none
		sourceColumn: rider_wait_time_minutes

	column order_ready_marked
		dataType: string
		summarizeBy: none
		sourceColumn: order_ready_marked

	column customer_complaint_tag
		dataType: string
		summarizeBy: none
		sourceColumn: customer_complaint_tag

	column customer_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: customer_id

	column distance_km
		dataType: double
		formatString: 0.0
		summarizeBy: none
		sourceColumn: distance_km

	column item_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: item_count

	partition OrderHistory = m
		mode: import
		source =
				let
					Source = Table.PromoteHeaders(
						Csv.Document(
							File.Contents(DataFolder & "order_history_clean.csv"),
							[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
						),
						[PromoteAllScalars = true]
					),
					Selected = Table.SelectColumns(
						Source,
						{
							"order_id", "restaurant_name", "subzone", "order_placed_at", "order_status", "discount_construct",
							"bill_subtotal", "total", "rating", "cancellation_reason", "kpt_duration_minutes",
							"rider_wait_time_minutes", "order_ready_marked", "customer_complaint_tag", "customer_id",
							"distance_km", "item_count"
						}
					),
					// Empty CSV fields arrive as "" in text columns - make them real blanks.
					EmptyToNull = Table.TransformColumns(
						Selected,
						{
							{"discount_construct", each if _ = "" then null else _},
							{"cancellation_reason", each if _ = "" then null else _},
							{"customer_complaint_tag", each if _ = "" then null else _}
						}
					),
					Typed = Table.TransformColumnTypes(
						EmptyToNull,
						{
							{"order_id", Int64.Type}, {"restaurant_name", type text}, {"subzone", type text},
							{"order_placed_at", type datetime}, {"order_status", type text}, {"discount_construct", type text},
							{"bill_subtotal", type number}, {"total", type number}, {"rating", Int64.Type},
							{"cancellation_reason", type text}, {"kpt_duration_minutes", type number},
							{"rider_wait_time_minutes", type number}, {"order_ready_marked", type text},
							{"customer_complaint_tag", type text}, {"customer_id", type text},
							{"distance_km", type number}, {"item_count", Int64.Type}
						},
						"en-US"
					),
					WithDate = Table.AddColumn(Typed, "OrderDate", each Date.From([order_placed_at]), type date),
					WithHour = Table.AddColumn(WithDate, "order_hour", each Time.Hour([order_placed_at]), Int64.Type),
					WithDiscountFlag = Table.AddColumn(WithHour, "has_discount", each [discount_construct] <> null, type logical)
				in
					WithDiscountFlag

	annotation PBI_ResultType = Table

